version: '3.0'

services:
  blog:
    environment:
      MEMCACHED_HOST: memcached
    image: nathamanath/blog:latest
    networks:
      - blog
    ports:
      - 9292:9292

  memcached:
    image: memcached:1.5.5-alpine
    networks:
      - blog

networks:
  blog: {}
